analyzer:
  errors:
    no_leading_underscores_for_local_identifiers: ignore
    must_be_immutable: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_const_constructors: false